#!/usr/bin/env python

import sys

from mob_manip_gui.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'mob_manip_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
